In [1]:
import numpy as np

In [2]:
class Perceptron:
    def __init__(self, input_size, lr=0.1):
        # +1 for the bias weight
        self.W = np.zeros(input_size + 1)
        self.lr = lr

    def activation_fn(self, x):
        return 1 if x >= 0 else 0

    def predict(self, x):
        # insert bias input of 1
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        return self.activation_fn(z)

    def train(self, X, Y, epochs):
        for _ in range(epochs):
            for i in range(Y.shape[0]):
                x = X[i]
                y_pred = self.predict(x)
                e = Y[i] - y_pred
                # update rule
                self.W += self.lr * e * np.insert(x, 0, 1)

# ASCII‐encoded inputs for digits 0–9
X = np.array([
    [0,0,0,0,0,0,1,0,0,0],  # '0'
    [0,0,0,0,0,0,0,1,0,0],  # '1'
    [0,0,0,0,0,0,0,0,1,0],  # '2'
    [0,0,0,0,0,0,0,0,0,1],  # '3'
    [0,0,0,0,0,0,1,1,0,0],  # '4'
    [0,0,0,0,0,0,1,0,1,0],  # '5'
    [0,0,0,0,0,0,1,1,1,0],  # '6'
    [0,0,0,0,0,0,1,1,1,1],  # '7'
    [0,0,0,0,0,0,1,0,1,1],  # '8'
    [0,0,0,0,0,0,0,1,1,1],  # '9'
])

# Labels: even→0, odd→1
Y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

# Instantiate and train
perceptron = Perceptron(input_size=10)
perceptron.train(X, Y, epochs=100)  # Training for 100 epochs :contentReference[oaicite:0]{index=0}:contentReference[oaicite:1]{index=1}

# Test on the same inputs
for x in X:
    y = perceptron.predict(x)
    print(f'{x} → {"even" if y == 0 else "odd"}')  # Testing outputs :contentReference[oaicite:2]{index=2}:contentReference[oaicite:3]{index=3}


[0 0 0 0 0 0 1 0 0 0] → even
[0 0 0 0 0 0 0 1 0 0] → odd
[0 0 0 0 0 0 0 0 1 0] → even
[0 0 0 0 0 0 0 0 0 1] → odd
[0 0 0 0 0 0 1 1 0 0] → even
[0 0 0 0 0 0 1 0 1 0] → even
[0 0 0 0 0 0 1 1 1 0] → even
[0 0 0 0 0 0 1 1 1 1] → even
[0 0 0 0 0 0 1 0 1 1] → even
[0 0 0 0 0 0 0 1 1 1] → odd
